---
version: '3.8'
volumes:
  jackett_config: {}
  redis_data: {}

services:
  annatar:
    image: docker.io/mikmc/annatarnew:latest
    ports:
      - "8000:8000"
    depends_on:
      - jackett
    volumes:
      - "redis_data:/app/data"
    environment:
      LOG_LEVEL: debug
      JACKETT_URL: "http://1.14.73.37:9117"
      JACKETT_API_KEY: "ft950g440swlqnrk8vpu35s533ok1fo8"
      JACKETT_MAX_RESULTS: "100"
      JACKETT_TIMEOUT: "60"
      JACKETT_INDEXERS: "btsow,hdarea,hdatmos,hdfans,monikadesign-api,passthepopcorn,thesceneplace,torlock,xspeeds"
      LISTEN_PORT: "8000"

  jackett:
    image: docker.io/linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - jackett_config:/config
