---
version: '3.8'
volumes:
  jackett_config: {}
  redis_data: {}

services:
  annatar:
    image: docker.io/mikmc/annatar:latest
    ports:
      - "8000:8000"
    depends_on:
      - jackett
    volumes:
      - "redis_data:/app/data"
    environment:
      LOG_LEVEL: "debug"
      JACKETT_URL: "http://1.14.73.37:9117"
      JACKETT_API_KEY: "ft950g440swlqnrk8vpu35s533ok1fo87"
      JACKETT_MAX_RESULTS: "10"
      JACKETT_TIMEOUT: "5"
      JACKETT_INDEXERS: "audiences,btsow,eztv,hdarea,hdatmos,hdfans,hdsky,milkie,monikadesign-api,ncore,passthepopcorn,thesceneplace,torlock"
      LISTEN_PORT: "8000"

  jackett:
    image: docker.io/linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - jackett_config:/config
